#!/usr/bin/env python3
"""Render the test game's two 480x272 pages with Japanese text and write
   scene.h (RGB565 arrays) + truth.json (per-character ink boxes in PSP pixels).

   The truth is measured from the rendered pixels themselves (each glyph is
   rendered alone on a blank page and its ink bounding box taken), so it is the
   exact box a perfect recognizer would return for that character.
   Font: Droid Sans Japanese (Apache 2.0) or Noto Sans CJK JP (OFL)."""
import json, os, sys
from PIL import Image, ImageDraw, ImageFont

W, H = 480, 272
FONT_CANDIDATES = [
    "/usr/share/fonts/google-droid-sans-fonts/DroidSansJapanese.ttf",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc",
]
FONT = next((f for f in FONT_CANDIDATES if os.path.exists(f)), None)
if not FONT:
    sys.exit("no Japanese font found; install google-droid-sans-fonts or Noto Sans CJK")

# Each page: background fills, then text runs (x, y = top-left of the em box).
PAGES = [
    {
        "bg": (12, 16, 28),
        "rects": [((0, 196, 480, 272), (18, 28, 52)), ((300, 40, 470, 150), (36, 32, 24))],
        "text": [
            {"x": 24, "y": 14, "size": 24, "color": (255, 255, 255), "text": "勇者の冒険"},
            {"x": 24, "y": 206, "size": 18, "color": (255, 255, 255), "text": "ここは静かな村だ。", "dialogue": True},
            {"x": 24, "y": 234, "size": 18, "color": (255, 255, 255), "text": "北の森には古い神殿があるらしい。", "dialogue": True},
            {"x": 316, "y": 50, "size": 16, "color": (255, 224, 120), "text": "アイテム"},
            {"x": 316, "y": 74, "size": 16, "color": (255, 224, 120), "text": "装備"},
            {"x": 316, "y": 98, "size": 16, "color": (255, 224, 120), "text": "魔法"},
            {"x": 316, "y": 122, "size": 16, "color": (255, 224, 120), "text": "セーブ"},
            {"x": 24, "y": 170, "size": 12, "color": (170, 180, 200), "text": "所持金一千二百"},
        ],
    },
    {
        "bg": (30, 12, 12),
        "rects": [((0, 180, 480, 272), (60, 20, 20))],
        "text": [
            {"x": 40, "y": 30, "size": 22, "color": (255, 240, 200), "text": "戦闘開始！"},
            {"x": 40, "y": 190, "size": 20, "color": (255, 255, 255), "text": "スライムが現れた。", "dialogue": True},
            {"x": 40, "y": 224, "size": 20, "color": (255, 255, 255), "text": "どうする？", "dialogue": True},
        ],
    },
]
MARK = 6  # corner marker size (white squares) used by the E2E to find the PSP frame in the canvas


def render(page, measure=False):
    img = Image.new("RGB", (W, H), page["bg"])
    d = ImageDraw.Draw(img)
    for box, col in page["rects"]:
        d.rectangle(box, fill=col)
    for cx, cy in [(0, 0), (W - MARK, 0), (0, H - MARK), (W - MARK, H - MARK)]:
        d.rectangle((cx, cy, cx + MARK - 1, cy + MARK - 1), fill=(255, 255, 255))
    truth = []
    for run in page["text"]:
        font = ImageFont.truetype(FONT, run["size"])
        x = run["x"]
        chars = []
        for ch in run["text"]:
            d.text((x, run["y"]), ch, font=font, fill=run["color"])
            # ink box: render the glyph alone and measure its pixels
            solo = Image.new("L", (W, H), 0)
            ImageDraw.Draw(solo).text((x, run["y"]), ch, font=font, fill=255)
            bbox = solo.point(lambda v: 255 if v >= 64 else 0).getbbox()  # ink >= 25% alpha
            if bbox:
                chars.append({"ch": ch, "x0": bbox[0], "y0": bbox[1], "x1": bbox[2], "y1": bbox[3]})
            x += font.getlength(ch)
        truth.append({"text": run["text"], "size": run["size"], "chars": chars})
    return img, truth


def rgb565(img):
    out = []
    for r, g, b in img.getdata():
        out.append(((b >> 3) << 11) | ((g >> 2) << 5) | (r >> 3))  # PSP 565 is B:5 G:6 R:5 (red in the low bits)
    return out


pages, truth = [], []
for p in PAGES:
    img, t = render(p)
    pages.append(img)
    truth.append(t)
with open("scene.h", "w") as f:
    f.write("/* generated by gen_scene.py — do not edit */\n#define PAGE_COUNT %d\n" % len(pages))
    # The dialogue line of each page as a Shift-JIS C string: the game keeps the current one in
    # a fixed RAM buffer (g_line) so text-hook (Agent-style) scripts can read it like a real game.
    f.write("#define LINE_BYTES 160\n")
    f.write("static const unsigned char LINES[PAGE_COUNT][LINE_BYTES] = {\n")
    for p in PAGES:
        line = "".join(r["text"] for r in p["text"] if r.get("dialogue"))
        b = line.encode("shift_jis") + b"\0"
        f.write("{" + ",".join(str(x) for x in b) + "},\n")
    f.write("};\n")
    f.write("static const unsigned short PAGES[PAGE_COUNT][%d] = {\n" % (W * H))
    for img in pages:
        px = rgb565(img)
        f.write("{")
        for i in range(0, len(px), 32):
            f.write(",".join(str(v) for v in px[i:i + 32]) + ",\n")
        f.write("},\n")
    f.write("};\n")
json.dump({"width": W, "height": H, "marker": MARK, "font": os.path.basename(FONT), "pages": truth, "dialogue": ["".join(r["text"] for r in p["text"] if r.get("dialogue")) for p in PAGES]}, open("truth.json", "w"), ensure_ascii=False, indent=1)
for i, img in enumerate(pages):
    img.save("page%d.png" % i)
print("wrote scene.h, truth.json, page*.png; glyphs:", [sum(len(r["chars"]) for r in t) for t in truth])
