TARGET = jptext
OBJS = main.o
CFLAGS = -O2 -G0 -Wall
LIBDIR =
LIBS =
EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = JP Text Alignment Test
PSPSDK = $(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
